### ISSUE TITLE
Server problem when Mongo is not running

### ISSUE THREAD

**Issue by anvk** [JaredHawkins/TweetGeoViz#67]
It is probably related to Promises.

If Mongo is not running and client requests tweets then server never responds back. I see only OPTIONS request in console but never GET.
Client should have its own timeout it is for sure, but server should be smart as well. If Mongo is down then it should return some HTTP error code back with an error message.

**Comment by carloscarcamo** [comment]
what about something like this?

```js
res.status(503).send('Database is down');
```

**Comment by anvk** [comment]
Or 'Database is not responding'. Maybe this is a better wording because there could be multiple issues related to connectivity even though database is up and running.

**Comment by carloscarcamo** [comment]
Now I'm trying to get connections errors but, in [monk's docs](https://github.com/Automattic/monk) I couldn't find any way to do this, it seems that monk doesn't provide a way to check for connection status.

For the moment I'm handling errors on promises  but, I this is not the best way to do it, because we don't know what kind of errors do we have, it could be connection error or errors in queries.

Nota: This is my first time using ```monk``` :)

**Comment by anvk** [comment]
Are you sure? Because I see that all promises have `error` handler
https://github.com/Automattic/monk#promises
https://github.com/Automattic/monk#streaming

I'm not a huge expert in monk either. If you believe some other NPM would make more sense and provide an explanation why so, we can totally switch.

**Comment by carloscarcamo** [comment]
Promises works well, I'm handling errors with promises but, the problem is when mongodb is not running, there is a bug related to this on monk's repo: https://github.com/Automattic/monk/issues/24
Maybe we can move to [node-mongoskin](https://github.com/kissjs/node-mongoskin) or [Mongoose](https://github.com/Automattic/mongoose)

**Comment by carloscarcamo** [comment]
@anvk I have some code using [node-mongoskin](https://github.com/kissjs/node-mongoskin) (note: monk is based on it) but, maybe you prefer another NPM package, if so, please let me know before I send a pull request.

**Comment by anvk** [comment]
@carloscarcamo could you do a little bit of a research on existing Mongo connectors in NPM and compare them. It just interesting to know at least some kind of a justification for picking one but not another.

**Comment by carloscarcamo** [comment]
Nice!
