### ISSUE TITLE
Research and pick one of the Mongo connectors

### ISSUE THREAD

**Issue by anvk** [JaredHawkins/TweetGeoViz#68]
It looks like Monk is not good enough because you cannot detect if Mongo server is down. We should pick another connector instead.

**Comment by carloscarcamo** [comment]
From mongodb website we have this information: https://docs.mongodb.org/ecosystem/drivers/node-js/
Since almost all npm mongodb packages are built on top of the official [Mongodb native driver](https://github.com/mongodb/node-mongodb-native), we have to choose between the native driver or another based on it which the most widely used are:

- [Mongoose](https://github.com/Automattic/mongoose)
- [Mongoskin](https://github.com/kissjs/node-mongoskin)
- [Mongojs](https://github.com/mafintosh/mongojs)

The most active of them is mongoose followed by Mongojs and Mongoskin which last commit was on october 2015.

I found another packages which look promising:

- [mongorito](https://github.com/vdemedes/mongorito)  based on ES6 generators
- [Iridium](https://github.com/SierraSoftworks/Iridium)
- [mongodb-next](https://github.com/mongodb-utils/mongodb-next)

I think choosing the right NPM package will depend on the project, right now we are just doing a basic find query no inserts and updates at this moment, but maybe this will change in the future. 
I have used `mongoose` before and it's great, `mongoskim` and `mongojs` are great also. 

If we want to use a ORM style we can choose `mongoose`, if not, we can go for `mongoskin` or `mongojs`

**Comment by anvk** [comment]
This is a great and thorough research. Great thanks @carloscarcamo I really appreciate it. You are totally right that we are just doing basic queries but picking a somewhat good library in the beginning can save us lots of pain down the road.
I trust to your judgement to use `mongoose` especially since you have some expertise in it already... I say let's go with `mongoose` for now.
