### ISSUE TITLE
Blank page on client side

### ISSUE THREAD

**Issue by carloscarcamo** [JaredHawkins/TweetGeoViz#70]
For testing purpose, I did `rm -rf node_modules` and then `npm install`, now I'm getting a blank page on client, my js console says: 

```
TypeError: action.location is undefined                                                  bundle.js (línea 38929, col 11)
```

See the screenshot below:

![captura de pantalla de 2016-01-25 23 53 54](https://cloud.githubusercontent.com/assets/2413746/12573457/ffe028ec-c3be-11e5-9b77-cde2bf095c31.png)

**Comment by anvk** [comment]
Ugh this is very very bad. My apologies I will try to fix it asap

**Comment by anvk** [comment]
@carloscarcamo can you try again please. If it works for you then I will close this ticket.

Also in order to debug code you can either put a breakpoint in the code in Chrome or FF to see why it fails there OR in case if you cannot put a breakpoint but you still want to stop the execution (like in this particular case) you can add `debugger;` in the code and then refresh browser running your webpack dev version.

No idea why but instead of looking into `action.payload` I was looking into `action.location` :S

**Comment by carloscarcamo** [comment]
@anvk now it works great! next time do what you suggest for debugging.
